## 1) 길이가 10인 0벡터(전부 0으로 채워진) 을 만드세요 (벡터는 array로 이해하시면 됩니다)

In [0]:
import numpy as np

a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 2) 길이는 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.


In [0]:
# 위 a 어레이를 그대로 이용합니다
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 3) 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [0]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4) 위 3)에서 만든 벡터의 순서를 바꾸세요.

요건 여러가지 방법이 있습니다.

In [0]:
# 방법 1.

%time print(b[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 3.87 ms


In [0]:
# 방법 2.

%time print(np.flipud(b))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
CPU times: user 911 µs, sys: 0 ns, total: 911 µs
Wall time: 789 µs


In [0]:
# 방법 3.

%time print(np.ascontiguousarray(b[::-1]))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
CPU times: user 362 µs, sys: 1.81 ms, total: 2.17 ms
Wall time: 1.88 ms


방법 1이 이해하기 가장 어렵지만 가장 빠릅니다.

파이썬의 list slicing을 응용한 방법으로써,

> **[(시작위치) : (끝위치) : (stepsize)]** 

로 이해하시면 되겠습니다

더 이해가 필요한 분은 [여기](https://stackoverflow.com/questions/15748001/reversed-array-in-numpy)를 보세요!

상세한 성능 비교는 아래와 같습니다

<br>

![대체 텍스트](https://i.stack.imgur.com/FI0f2.png)

## 5) 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [0]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6) 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [0]:
x = np.array([1,2,0,0,4,0])

%time x[x > 0]
print(x[x > 0])

%time x[x != 0]
print(x[x != 0])

CPU times: user 27 µs, sys: 7 µs, total: 34 µs
Wall time: 36.7 µs
[1 2 4]
CPU times: user 17 µs, sys: 4 µs, total: 21 µs
Wall time: 23.8 µs
[1 2 4]


## 7) 3x3 단위 행렬(행렬의 좌측상단 ~ 우측하단 대각선만 전부 1이고 나머지는 모두 0)을 만드세요

In [0]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

대각선의 방향을 바꾸려면 위에 예제를 응용해 다음과 같이 하면됩니다

In [0]:
np.eye(3,3)[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

## 8) 난수 원소를 가지는 3x3 행렬을 만드세요

In [0]:
arr = np.random.random((3,3))

import pandas as pd

a = pd.DataFrame(arr)
a

0         1         2
0  0.233275  0.908670  0.518965
1  0.355762  0.895966  0.962955
2  0.710228  0.283592  0.699674

## 9) 위 8)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [0]:
print(arr.max())
print(arr.min())

0.9629554096667262
0.23327478116345912


## 10) 위 8)에서 만든 난수 행렬에서 각 행의 평균, 각 열 평균을 계산하세요.

In [0]:
print('행 평균: ' , arr.mean(axis = 1))
print('열 평균: ' , arr.mean(axis = 0))

행 평균:  [0.55363647 0.73822782 0.56449799]
열 평균:  [0.43308817 0.69607589 0.72719821]


In [0]:
print(arr[0])
print(arr[0].mean())

[0.23327478 0.90866987 0.51896477]
0.5536364739170555


In [0]:
arr.sum(axis = 0)

array([1.29926451, 2.08822768, 2.18159464])